
import Head from "next/head";
import Layouts from "../components/Layouts";
import Image from "next/image";
import profilePic from "../../public/images/profile/Programming-pana.png";
import AnimatedText from "../components/AnimatedText";
import TransitionEffect from "../components/TransitionEffect";
import React, { useRef } from "react";
import emailjs from "@emailjs/browser";

const contact = () => {
  const form = useRef();

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs
      .sendForm(
        "service_bbt19ta",
        "template_3cqxspt",
        form.current,
        "_Mdd6LqYXsZ5u2vKaY"
      )
      .then(
        (result) => {
          console.log(result.text);
          console.log("message sent");
        },
        (error) => {
          console.log(error.text);
        }
      );
  };
  return (
    <>
      <Head>
        <title>Jacky| Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light 2xl:">
        <Layouts className="pt-0 md:pt-16 sm:pt-8"></Layouts>

        <form ref={form} onSubmit={sendEmail}>
          <label>Name</label>
          <input type="text" name="user_name" />
          <label>Email</label>
          <input type="email" name="user_email" />
          <label>Message</label>
          <textarea name="message" />
          <input type="submit" value="Send" />
        </form>
      </main>
    </>
  );
};

export default contact;
