import Head from "next/head";
import Layouts from "../components/Layouts";
import Image from "next/image";
import profilePic from "../../public/images/profile/Home-page.png";
import AnimatedText from "../components/AnimatedText";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layouts className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={profilePic} alt="jacky" className="w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col item-center self-center">
              <AnimatedText
                text="Turning Visions Into Reality With Code And Design."
                className="!text-6x1 !text-left "
              />
              <p className="my-4 text-base font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects showcasing my expertise in web development!
              </p>
            </div>
          </div>
        </Layouts>
      </main>
    </>
  );
}
